### PR TITLE
Add J5

### PR DESCRIPTION
**Pull request by SoUnd001**

### CODE REVIEW

**Comment by anupritaisno1** [comment]
Hey @SoUnd001 learn to write proper commits
Let me ask you this, do you see anyone at aosp or CAF making "update this" commits?

**Comment by anupritaisno1** [comment]
@anupritaisno1 @SoUnd001

**Comment by poad42** [comment]
@anupritaisno1 Look who is talking

**Comment by coolmihir** [comment]
@poad42 Lel 😂

**Pull request merged**
